apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=        # base64 for 'postgres'
  DB_PASSWORD: cG9zdGdyZXM=    # base64 for 'postgres'
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0 # base64 for 'your_jwt_secret'
