-- -- CREATE TABLE IF NOT EXISTS users (
-- --   id SERIAL PRIMARY KEY,
-- --   email VARCHAR(100) UNIQUE NOT NULL,
-- --   password VARCHAR(255) NOT NULL
-- -- );
-- -- CREATE TABLE IF NOT EXISTS users (
-- --   id SERIAL PRIMARY KEY,
-- --   email VARCHAR(100) UNIQUE NOT NULL,
-- --   password VARCHAR(255) NOT NULL
-- -- );


-- CREATE TABLE IF NOT EXISTS users (
--   id SERIAL PRIMARY KEY,
--   name VARCHAR(100) NOT NULL,
--   email VARCHAR(100) UNIQUE NOT NULL,
--   password VARCHAR(255) NOT NULL
-- );

-- ALTER TABLE users ADD COLUMN name VARCHAR(100) NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
